server:
  port: 8080
  servlet:
    context-path: /v1

application:
  timezone: Asia/Shanghai

spring:
  application:
    name: frauddetector
  datasource:
    url: jdbc:mariadb://localhost:3306/demo_db?useSSL=false&serverTimezone=UTC
    username: remote_user
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  rocketmq:
    name-server: rocketmq:9876
    producer:
      group: defaultProducerGroup
    consumer:
      group: defaultConsumerGroup

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.johnnydemo.frauddetector.entity

drools:
  bean:
    scan:
      enabled: true
  kmodule:
    enabled: true